### ISSUE TITLE
Content for main page

### ISSUE THREAD

**Issue by BreadandYeast** [CammoSz/HTML#5]
From assignment brief:
- include offer a brief specification of the course
- How they will be assessed
- What equipment they may need
- Where they would study with images of the lab and resources
- Where and how to apply
- allow students to download the specification (okay??)
- have internal and external links to appropriate sites for further information for example to information on Youtube

**Comment by ghost** [comment]
Text is a bit too spaced out and I cant figure out how to place the image without expanding the div and adding a bunch of useless whitespace. Should be a easy fix however.

**Comment by ghost** [comment]
Basically done, but text is spaced out and the image adds unnecessary whitespace, fix in resub.
